apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quarkus-0423-2
  janus-idp.io/tekton: quarkus-0423-2
  backstage.io/kubernetes-id: quarkus-0423-2
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quarkus-0423-2
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
